version: '3'

services:
  arangodb:
    image: arangodb/arangodb:3.11.8
    container_name: arangodb
    environment:
      - ARANGO_ROOT_PASSWORD=openSesame
    ports:
      - "8529:8529"

  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python-app
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app
    depends_on:
      - arangodb
    command: ["tail", "-f", "/dev/null"]